#' CGPSS Respondent Characteristics
#'
#' Return a list of fields describing CGPSS respondents
#' @export
cgpss_respondent_characteristics <- function() {
  c(cgpss_excluded_fields(),
  c( 'SV_ALTRECORDNUM',
     'SURVEY_YEAR',
     'THESIS',
     'DEGREE_SELF_REPORT',
     'DISCIPLINE_COMBINED',
     'DISCIPLINE_SPECIFIED',
     'GENDER',
     'AGE',
     'RESIDENCE',
     'MARITAL',
     'CHILDREN',
     'CITIZEN',
     'CITIZENOTHER_SPECIFIED',
     'YEARSTUDY',
     'GBLACK',
     'GEASTASIA',
     'GSOUTHASIA',
     'GSOUTHEASTASIA',
     'GWESTASIA',
     'GLATINAM',
     'GMIXED',
     'NONE',
     'GMIXEDOTHER',
     'ABORIGINAL',
     'DISABLSELFID',
     'DISABL_SENSE',
     'DISABL_MOBIL',
     'DISABL_LEARN',
     'DISABL_MENTAL',
     'DISABL_AUTISM',
     'DISABL_CHRONIC',
     'DISABL_ELSE',
     'DISABL_ELSE_SPECIFIED',
     'DISABL_NOTRESPOND'))
}

#' CGPSS Excluded Fields
#'
#' Return a list of non-question CGPSS fields.
#'
#' In order to exclude non-question bits from the response
#' table, we need a list of fields that aren't questions.
#' @export
cgpss_excluded_fields <- function() {
  c('Language',
    'LANGUAGE',
    'SV_UNIV',
    'SV_YEAR',
    'UNIV_PROGRAM_NAME',
    'UNIV_ORIGINAL_CIP',
    'UNIV_IMMIGRATION',
    'UNIV_YEARSTUDY',
    'UNIV_GENDER',
    'UNIV_PROGRAM_LEVEL',
    'UNIV_ACADLOAD',
    'UNIV_FACULTY',
    'UNIV_ACRONYM',
    'UNIV_ACRONYM_DESC',
    'UNIV_IMPOSE_STREAM',
    'CUSTOM_1',
    'CUSTOM_2',
    'CUSTOM_3',
    'CUSTOM_4',
    'CUSTOM_5',
    'UNIV_DISCIPLINE',
    'UNIV_DISCIPLINE_DIM_FR',
    'UNIV_DISCIPLINE_DIM_EN',
    'UNIV_CLUSTER',
    'UNIV_CLUSTER_DIM_FR',
    'UNIV_CLUSTER_DIM_EN',
    'ACTUAL_STREAM',
    'ACTUAL_STREAM_DIM',
    'UNIV_DEGREE',
    'UNIV_DEGREE_DIM',
    'STARTED',
    'COMPLETED',
    'MODIFIED',
    'CONTACT_EMAIL',
    'OPENING_DATE',
    'CLOSING_DATE',
    'TIME_OUT',
    'INSTITUTION_SIZE',
    'REGION',
    'LAST_PAGE',
    'SV_ACTUAL_STREAM_DIM',
    'SV_DEGREE',
    'SV_DEGREE_DIM',
    'SV_YEAR',
    'SV_REGION',
    'SV_CIP_CHANGED',
    'SV_INSTRUMENT2010',
    'SV_UGDEBT_DIM',
    'SV_DEGREE_DIM',
    'SV_ETHNICITY_DIM',
    'SV_CUBC',
    'SV_CLUSTER_DIM_EN',
    'SV_CLUSTER',
    'SV_AGEMED',
    'SV_DISCIPLINE',
    'SV_RECORDKEY',
    'SV_EDITED_CIP',
    'SV_GDEBTD',
    'SV_UGDEBTD',
    'SV_CLUSTER_DIM_FR',
    'SV_SIZE',
    'SV_RECORDNUM',
    'SV_GDEBT',
    'SV_COMPLETED',
    'SV_ETHNICITY',
    'SV_DISCIPLINE_DIM_FR',
    'SV_UGDEBT',
    'SV_GDEBT_DIM',
    'SV_DISCIPLINE_DIM_EN',
    'SV_ACTUAL_STREAM',
    'SV_ACTUAL_STREAM_DIM'
    )
}
